# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ETmfsTGsr-CwvEYStRJPqU9nCMEdVWbV
"""

num1=float(input("Enter the temperature in Celsius scale:"))
num1
f=(num1*1.8+32)
print("The temperature in Farhenheit is:",f)

import math
r=float(input("Enter the radius of the circle:"))
area=(math.pi * r*r)
print (" The area of the circle is:", area)

peri=(math.pi*2*r)
print ("The perimeter of the circle is:", peri)

import math
amount=float(input("Enter the principal amount:"))
intrest=float(input("Enter the intrest percentage:"))
final=(amount*intrest/100)+amount
print("The new amount is:",final)

import math
meter=float(input("Enter the distance in meter to be converted into centimeters,inches ,yards: "))
centimeters=meter*100
inches=meter*39.3700787
yards=meter*1.0936133
print("",meter,"meter is equal to ",centimeters,"centimeter,",inches,"inches,",yards,"yards")

actual_cost = float(input("Enter the actual cost of the product: "))
selling_cost = float(input("Enter the selling cost of the product: "))

if selling_cost > actual_cost:
  profit = selling_cost - actual_cost
  print("Profit is:", profit)
elif actual_cost > selling_cost:
  loss = actual_cost - selling_cost
  print("Loss is:", loss)
else:
  print("No profit, no loss.")

basic=float(input("Enter the basic salary:"))
da=0.75*basic
hra=0.20*basic
if basic <10000:
  gross=da+basic
  print("Gross salary is:",gross)
elif basic >=10000 and basic <20000:
  gross=da+basic+0.5*hra
  print("Gross salary is:",gross)
else:
  gross=basic+da+hra
  print("Gross salary is:",gross)

def factorial(n):
  if n == 0:
    return 1
  else:
    return n * factorial(n-1)
num = int(input("Enter a number: "))
if num < 0:
  print("Factorial is not defined for negative numbers.")
else:
  result = factorial(num)
  print(f"The factorial of {num} is {result}")

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

sum = 0
for i in range(num1, num2 + 1):
  sum += i

print("The sum of numbers between", num1, "and", num2, "is:", sum)

num = (56,2,35,41,43,48,32,56,71,55,68)
even_numbers = []
odd_numbers = []
for i in num:
  if i%2==0:
    even_numbers.append(i)
  else:
    odd_numbers.append(i)
print("Even numbers list:",even_numbers)
print("Odd numbers list:",odd_numbers)

def check_even_odd(num):
  if num % 2 == 0:
    print(num, "is even.")
  else:
    print(num, "is odd.")

number = int(input("Enter a number: "))
check_even_odd(number)

import math

num = float(input("Enter a number: "))


sqrt_num = math.sqrt(num)
print("Square root:", sqrt_num)

sin_num = math.sin(math.radians(num))
print("Sin:", sin_num)


tan_num = math.tan(math.radians(num))
print("Tan:", tan_num)


log_num = math.log10(num)
print("Log (base 10):", log_num)


if num.is_integer():
  num = int(num)
  if num >= 0:
    factorial_num = math.factorial(num)
    print("Factorial:", factorial_num)
  else:
    print("Factorial is not defined for negative numbers.")
else:
  print("Factorial is only defined for integers.")

class Rectangle:
  def __init__(self, length, width):
    self.length = length
    self.width = width

  def calculate(self):
    return self.length * self.width


my_rectangle = Rectangle(5, 10)
area = my_rectangle.calculate()
print("Area of the rectangle:", area)